language: python
python:
  - "3.9"

env:
  - TOX_ENV=py39-django-31
  - TOX_ENV=py39-django-32

cache:
  directories:
    - .venv

matrix:
  fast_finish: true

before_install: pip install poetry tox-travis
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
